from .createUser import *
from .logUser import *
from .logOutUserPong import *
from .uploadAvatar import *
from .setUsername import *
from .setMail import *
from .setPassword import *
from .set2FA import *
from .validateCode2FA import *
from .setFollow import *
from .setRequestFollow import *
from .setMatch import *
from .setTournament import *
from .setStatus import *
from .unsetFollow import *
